# 16.异常处理方式之一_捕获异常

<a name="9ZWiP"></a>
## 导问
1. 捕获异常所使用的关键字有哪些？
  1. try catch,final
2. try-catch-finally有几种结合形式，每种组合形式的执行顺序是什么？
  1. try-catch组合,正常执行try以及try catch之后的,是根本不会执行到catch块以外的内容的,异常会执行到catch的内容
  1. try-finally组合,正常执行try,无论是否异常,都会执行finally
  1. try-catch-finally组合,正常执行try以及try catch之后的,是根本不会执行到catch块以外的内容的,异常会执行到catch的内容,但同样无论是否异常都会执行到finally的内容

![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559699649526-d51a5426-6ab4-47de-bb19-3bfd9b099197.png#align=left&display=inline&height=28&name=image.png&originHeight=28&originWidth=320&size=12813&status=done&width=320)<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559699691131-a84d61bb-19b5-4ce9-8170-91b5b27f05bd.png#align=left&display=inline&height=46&name=image.png&originHeight=46&originWidth=357&size=10156&status=done&width=357)<br />正常情况会执行try以及trycatch以后的程序,是根本不会执行到catch块以内的内容的<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559699776065-0b779941-b78e-4968-b1a7-feba0c860d61.png#align=left&display=inline&height=179&name=image.png&originHeight=179&originWidth=368&size=31038&status=done&width=368)

try没问题,将会跳到catch以后的代码<br />如果出现异常<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559699860175-c203d1df-eefa-45cf-982d-428d9a1b3e1d.png#align=left&display=inline&height=158&name=image.png&originHeight=158&originWidth=369&size=45919&status=done&width=369)<br />除数为0会报算数异常错误<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559699927382-83a38bd1-b90e-4c2e-8cc0-540d849a3080.png#align=left&display=inline&height=327&name=image.png&originHeight=327&originWidth=705&size=167912&status=done&width=705)<br />此时程序并没有中断而是继续执行<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700288532-da97ca61-04d4-4565-afcf-2c9b324ca54c.png#align=left&display=inline&height=238&name=image.png&originHeight=238&originWidth=1120&size=209725&status=done&width=1120)<br />运行过程中由java虚拟机产生的一个异常对象,赋给了e去做引用<br />接着调用了<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700457022-199c7211-1bcf-49ba-ba6f-40d7a78bb663.png#align=left&display=inline&height=60&name=image.png&originHeight=60&originWidth=231&size=17275&status=done&width=231)<br />打印堆栈信息的方法,进而把异常给打印出来<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700549488-1c240dfb-1466-432c-84e0-bddcab3c1ed3.png#align=left&display=inline&height=59&name=image.png&originHeight=59&originWidth=676&size=42023&status=done&width=676)产生异常的位置

异常类型不匹配,如除数我输入a<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700592819-042980ca-701b-41ae-b931-09fff8d1e2ad.png#align=left&display=inline&height=273&name=image.png&originHeight=273&originWidth=555&size=167518&status=done&width=555)<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700609036-7b3b521f-fedd-4d29-87bf-d74fa22747ea.png#align=left&display=inline&height=36&name=image.png&originHeight=36&originWidth=323&size=14508&status=done&width=323)<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700621828-95378f3c-20aa-44fd-896b-a13285717ad3.png#align=left&display=inline&height=149&name=image.png&originHeight=149&originWidth=350&size=33098&status=done&width=350)<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700654547-ba20ed4c-af44-4c51-a7ac-24eaa600e5da.png#align=left&display=inline&height=40&name=image.png&originHeight=40&originWidth=1022&size=61934&status=done&width=1022)<br />因为创建异常对象不成功,因此不会进入catch内部的代码里进行执行,而执行了try就结束了

![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700693013-f92da805-34dc-452e-8d92-8bb39546ede3.png#align=left&display=inline&height=128&name=image.png&originHeight=128&originWidth=640&size=66818&status=done&width=640)

![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700718729-615c97ab-92d7-46de-a7d9-70831a5be0bb.png#align=left&display=inline&height=298&name=image.png&originHeight=298&originWidth=740&size=221348&status=done&width=740)<br />如果输入<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700738192-131291d2-277b-46d0-83b2-a5e61788a6f5.png#align=left&display=inline&height=144&name=image.png&originHeight=144&originWidth=433&size=61889&status=done&width=433)<br />finally中的代码依然执行了

不过finally有一种情况下是不执行的,那就是退出了java虚拟机<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700808124-1eabc38e-5139-4f55-8ba6-29785bfec31f.png#align=left&display=inline&height=332&name=image.png&originHeight=332&originWidth=725&size=161953&status=done&width=725)<br />这是finally代码唯一不执行的情况

第三种<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700838580-f900d793-4505-4f01-b141-535ddd5af313.png#align=left&display=inline&height=163&name=image.png&originHeight=163&originWidth=600&size=84433&status=done&width=600)<br />如<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700939034-8e40bbb1-571c-4842-a82e-69d29c5d60cc.png#align=left&display=inline&height=86&name=image.png&originHeight=86&originWidth=532&size=51800&status=done&width=532)<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700976616-9bbc4408-eeba-46e7-bf2e-9330f36c35fa.png#align=left&display=inline&height=78&name=image.png&originHeight=78&originWidth=753&size=57008&status=done&width=753)<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559700991225-a0d6721d-6bc9-4305-a127-071ef2254496.png#align=left&display=inline&height=41&name=image.png&originHeight=41&originWidth=445&size=34046&status=done&width=445)

![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559701070989-9dafe603-eea0-40a1-b642-4cf0c0f0cd41.png#align=left&display=inline&height=312&name=image.png&originHeight=312&originWidth=619&size=130814&status=done&width=619)<br />执行完finally再执行return去结束方法
