# 17.异常处理方式之二_声明异常


1. 继承关系中如何声明异常？
  1. 在父类方法名后面加上trows +异常类型
2.  throw与throws的区别是什么？
  1. throws用于声明方法可能会产生的异常类型,throw手动抛出异常对象
  1. throws写在方法名称后面,throw写在方法里

![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559701549404-dd6a61e7-a2d2-4da3-90be-3712338c94ab.png#align=left&display=inline&height=211&name=image.png&originHeight=211&originWidth=407&size=90863&status=done&width=407)<br />声明一个方法可能会产生异常<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559701269562-0da23eb3-3a6a-4618-a28d-b0c788e284b8.png#align=left&display=inline&height=77&name=image.png&originHeight=77&originWidth=384&size=17673&status=done&width=384)<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559701301280-8bee98f6-2e9c-4db4-9ad4-df59fb992a5c.png#align=left&display=inline&height=225&name=image.png&originHeight=225&originWidth=403&size=82643&status=done&width=403)<br />一个方法一旦使用了throws去声明一个exception异常或者一个检查时异常,那么在方法处一定要处理<br />两种处理方式,一种是不处理继续向上声明<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559701435156-c68a2f0d-9faf-4cb6-b81a-690249152f08.png#align=left&display=inline&height=71&name=image.png&originHeight=71&originWidth=438&size=29542&status=done&width=438)<br />如果依旧不处理就可以进行try catch<br />运行时异常可以不做处理<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559701576229-7f0f82fb-8648-414f-9c2a-12d77765be8e.png#align=left&display=inline&height=273&name=image.png&originHeight=273&originWidth=473&size=88466&status=done&width=473)

exception因为包括两个因此也要都做处理


继承<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559701632514-48aa5815-c4a7-457c-887d-9a07bb55166b.png#align=left&display=inline&height=140&name=image.png&originHeight=140&originWidth=389&size=55759&status=done&width=389)<br />不声明异常子类不报错<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559701730968-e85e9e7b-035d-44cd-b5d6-f6554f259948.png#align=left&display=inline&height=181&name=image.png&originHeight=181&originWidth=364&size=47997&status=done&width=364)<br />如果调用父类方法就必须去处理了<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559701755614-6b8358a9-20a2-45c7-a360-ef7223626a45.png#align=left&display=inline&height=216&name=image.png&originHeight=216&originWidth=370&size=63862&status=done&width=370)<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559701870785-29251604-1084-4c05-b667-339a66a3a41d.png#align=left&display=inline&height=80&name=image.png&originHeight=80&originWidth=370&size=42477&status=done&width=370)<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559702007314-8dcae532-5183-40ef-9c1a-6665c1530f32.png#align=left&display=inline&height=275&name=image.png&originHeight=275&originWidth=397&size=89987&status=done&width=397)<br />不能向上声明,因为父类是没有IOExcepion<br />可以在父类中加上异常声明<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559702098731-278bc171-8487-47ff-be8a-8fdf9e792155.png#align=left&display=inline&height=263&name=image.png&originHeight=263&originWidth=400&size=73287&status=done&width=400)<br />如果子类在重写父类方法时,产生的异常是runtimeexception,就可不处理了<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559702183162-d635e3c8-5e3a-4c43-8bad-bbb5c23c333b.png#align=left&display=inline&height=57&name=image.png&originHeight=57&originWidth=403&size=37125&status=done&width=403)

![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559702269194-f734ce42-41b1-42fe-b37b-37fffca35a89.png#align=left&display=inline&height=130&name=image.png&originHeight=130&originWidth=358&size=46413&status=done&width=358)<br />手动抛出异常<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559702342760-879c4059-7c74-45a3-82b9-156be91a22f5.png#align=left&display=inline&height=135&name=image.png&originHeight=135&originWidth=375&size=47550&status=done&width=375)

区别<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/349894/1559702403934-33642dcf-21cc-4608-a966-900fbea05186.png#align=left&display=inline&height=144&name=image.png&originHeight=144&originWidth=326&size=38119&status=done&width=326)<br />1.trows用于声明方法可能会产生的异常类型,throw手动抛出异常对象<br />2.trows写在方法名称后面,throw写在方法里
